version: '3.9'

services:
  database:
    image: postgres:14
    # ...
    networks:
      - dev_network

  backend:
    build:
      context: ./eduplanner-server
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/edudb
      # ...
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev_network
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./eduplanner-app
      dockerfile: Dockerfile
    environment:
      # nawet jeśli nazywasz się dev, możesz wstawić np. ENV=dev
      NODE_ENV: production
    networks:
      - dev_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  dev_network:
    driver: bridge
