version: '3.9'

services:
  database:
    image: postgres:14
    container_name: eduplanner-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: edudb
    ports:
      - "5432:5432"
    # DODAJEMY healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d edudb"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - dev_network

  backend:
    build:
      context: ./eduplanner-server
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/edudb
      # ...
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dev_network
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./eduplanner-app
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    networks:
      - dev_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  dev_network:
    driver: bridge
