version: '3.9'

services:
  database:
    image: postgres:14
    container_name: eduplanner-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: edudb
    volumes:
      - eduplanner-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d edudb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deploy_network

  backend:
    build:
      context: ./eduplanner-server
      dockerfile: Dockerfile
    container_name: eduplanner-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://eduplanner-database:5432/edudb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - deploy_network

  frontend:
    build:
      context: ./eduplanner-app
      dockerfile: Dockerfile
    container_name: eduplanner-frontend
    ports:
      - "3000:3000"
    networks:
      - deploy_network

networks:
  deploy_network:
    driver: bridge

volumes:
  eduplanner-db-data: {}
