name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v3
      with:
        path: eduplaner-deploy
        clean: true

    - name: Checkout server repository
      uses: actions/checkout@v3
      with:
        repository: Monkey-Business-z-o-o/eduplanner-server
        ref: dev
        token: ${{ secrets.DDToken }}
        path: eduplaner-deploy/eduplanner-server
        clean: true
        submodules: true

    - name: Checkout app repository
      uses: actions/checkout@v3
      with:
        repository: Monkey-Business-z-o-o/eduplanner-app
        ref: dev
        token: ${{ secrets.DDToken }}
        path: eduplaner-deploy/eduplanner-app
        clean: true
        submodules: true

    - name: Install dependencies on runner
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
        sudo chmod +x /usr/local/bin/cloudflared

    - name: Configure SSH for Cloudflare Tunnel
      run: |
        mkdir -p ~/.ssh
        echo "Host ssh.kebson.fun
          ProxyCommand cloudflared access ssh --hostname %h
          User edutest
          Port 222
        " >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Test SSH connection
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "echo Connection successful"

    - name: Ensure destination directory exists
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "mkdir -p /srv/EduTest"

    - name: Cleanup previous deployment
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "
        cd /srv/EduTest &&
        docker-compose down --rmi all || echo 'No previous containers to stop'
        rm -rf /srv/EduTest/*
        "

    - name: Transfer repositories to server
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e scp -r ./eduplaner-deploy edutest@ssh.kebson.fun:/srv/EduTest/

    - name: Build and start new containers
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "
        cd /srv/EduTest/eduplaner-deploy &&
        docker-compose pull &&
        docker-compose up --build -d
        "

    - name: Print image and container information
      env:
        SSHPASS: ${{ secrets.EDUTEST }}
      run: |
        sshpass -e ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "
        docker images &&
        docker ps -a
        "
