name: Deploy to Dev Environment

on:
  push:
    branches:
      - dev
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install cloudflared
      run: |
        curl -LO https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
        sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared
        sudo chmod +x /usr/local/bin/cloudflared

    - name: Install sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Configure SSH for Cloudflare Tunnel
      run: |
        mkdir -p ~/.ssh
        echo "Host ssh.kebson.fun
          ProxyCommand cloudflared access ssh --hostname %h
          User edutest
          Port 222
        " >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Test SSH connection
      run: |
        sshpass -p 'Dupa12345' ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "echo Connection successful"

    - name: Ensure application directories exist
      run: |
        sshpass -p 'Dupa12345' ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "
        mkdir -p /srv/eduplanner-deploy &&
        mkdir -p /srv/eduplanner-server
        "

    - name: Transfer application files to server
      run: |
        sshpass -p 'Dupa12345' scp -r ../eduplanner-deploy edutest@ssh.kebson.fun:/srv/ &&
        sshpass -p 'Dupa12345' scp -r ../eduplanner-server edutest@ssh.kebson.fun:/srv/

    - name: Deploy application
      run: |
        sshpass -p 'Dupa12345' ssh -o StrictHostKeyChecking=no edutest@ssh.kebson.fun "
        cd /srv/eduplanner-deploy &&
        docker-compose down &&
        docker-compose up --build -d
        "
